name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Configure git
        run: |
          git config --global user.email ci@example.com
          git config --global user.name CI
          git config --global init.defaultBranch main
      - name: Install dependencies
        run: pip install pytest
      - name: Run tests
        run: python3 -m pytest -q
